INSERT INTO Users (firstname, lastname, email, username, password) VALUES 
('Alice', 'Smith', 'alice.smith@example.com', 'alice_smith', 'hashed_password_1'),
('Bob', 'Johnson', 'bob.johnson@example.com', 'bob_johnson', 'hashed_password_2'),
('Carol', 'Davis', 'carol.davis@example.com', 'carol_davis', 'hashed_password_3'),
('David', 'Wilson', 'david.wilson@example.com', 'david_wilson', 'hashed_password_4'),
('Eva', 'Taylor', 'eva.taylor@example.com', 'eva_taylor', 'hashed_password_5'),
('Frank', 'Moore', 'frank.moore@example.com', 'frank_moore', 'hashed_password_6'),
('Grace', 'Jackson', 'grace.jackson@example.com', 'grace_jackson', 'hashed_password_7'),
('Hank', 'Martin', 'hank.martin@example.com', 'hank_martin', 'hashed_password_8'),
('Ivy', 'Lee', 'ivy.lee@example.com', 'ivy_lee', 'hashed_password_9'),
('Jack', 'White', 'jack.white@example.com', 'jack_white', 'hashed_password_10'),
('Kim', 'Harris', 'kim.harris@example.com', 'kim_harris', 'hashed_password_11'),
('Leo', 'Clark', 'leo.clark@example.com', 'leo_clark', 'hashed_password_12'),
('Mia', 'Lewis', 'mia.lewis@example.com', 'mia_lewis', 'hashed_password_13'),
('Nina', 'Robinson', 'nina.robinson@example.com', 'nina_robinson', 'hashed_password_14'),
('Owen', 'Walker', 'owen.walker@example.com', 'owen_walker', 'hashed_password_15'),
('Pam', 'Hall', 'pam.hall@example.com', 'pam_hall', 'hashed_password_16'),
('Quinn', 'Allen', 'quinn.allen@example.com', 'quinn_allen', 'hashed_password_17'),
('Ray', 'Young', 'ray.young@example.com', 'ray_young', 'hashed_password_18'),
('Sara', 'King', 'sara.king@example.com', 'sara_king', 'hashed_password_19'),
('Tom', 'Wright', 'tom.wright@example.com', 'tom_wright', 'hashed_password_20'),
('Uma', 'Scott', 'uma.scott@example.com', 'uma_scott', 'hashed_password_21'),
('Vera', 'Green', 'vera.green@example.com', 'vera_green', 'hashed_password_22'),
('Will', 'Adams', 'will.adams@example.com', 'will_adams', 'hashed_password_23'),
('Xena', 'Baker', 'xena.baker@example.com', 'xena_baker', 'hashed_password_24'),
('Yara', 'Gonzalez', 'yara.gonzalez@example.com', 'yara_gonzalez', 'hashed_password_25'),
('Zane', 'Nelson', 'zane.nelson@example.com', 'zane_nelson', 'hashed_password_26'),
('Alina', 'Carter', 'alina.carter@example.com', 'alina_carter', 'hashed_password_27'),
('Ben', 'Mitchell', 'ben.mitchell@example.com', 'ben_mitchell', 'hashed_password_28'),
('Cathy', 'Perez', 'cathy.perez@example.com', 'cathy_perez', 'hashed_password_29'),
('Derek', 'Roberts', 'derek.roberts@example.com', 'derek_roberts', 'hashed_password_30');

INSERT INTO Roles (role_name) VALUES 
('Front-end'), ('Back-end'), ('Data Science'),
('Data Analytics'), ('AI'), ('ML'),
('UI/UX'), ('2D Game Dev'), ('3D Game Dev'),
('VR'), ('AR'), ('Cyber Security'),
('Full Stack');

INSERT INTO Languages (language_name) VALUES 
('Python'), ('JavaScript'), ('Java'),
('Swift'), ('Ruby'), ('Kotlin'),
('React.js'), ('Vue.js'), ('Node.js'),
('Django'), ('Flask'), ('ASP.NET'),
('MySQL'), ('PostgreSQL'), ('MongoDB'),
('R'), ('NoSQL'), ('TypeScript'),
('C++');


INSERT INTO ProjectInterests (interest_name) VALUES 
('VR'), ('AR'), ('AI'), ('ML'), ('2D Game Dev'),
('3D Game Dev'), ('Web Dev'), ('Software Engineering'),
('Cyber Security');

INSERT INTO UserRoles (user_id, role_id) VALUES
(1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
(6, 6), (7, 7), (8, 8), (9, 9), (10, 10),
(11, 11), (12, 12), (13, 13), (14, 1), (15, 2),
(16, 3), (17, 4), (18, 5), (19, 6), (20, 7),
(21, 8), (22, 9), (23, 10), (24, 11), (25, 12),
(26, 13), (27, 1), (28, 2), (29, 3), (30, 4);

INSERT INTO UserLanguages (user_id, language_id) VALUES
(1, 1), (1, 2), (1, 3), 
(2, 1), (2, 2), 
(3, 4), (3, 5), 
(4, 6), (4, 7), 
(5, 1), (5, 2), (5, 3),
(6, 4), (6, 5), 
(7, 6), (7, 7), 
(8, 8), (8, 1), 
(9, 2), (9, 3),
(10, 4), (10, 5), 
(11, 6), (11, 7), 
(12, 8), (12, 1), 
(13, 2), (13, 3),
(14, 4), (14, 5),
(15, 6), (15, 7),
(16, 8), (16, 1),
(17, 2), (17, 3),
(18, 4), (18, 5),
(19, 6), (19, 7),
(20, 8), (20, 1),
(21, 2), (21, 3),
(22, 4), (22, 5),
(23, 6), (23, 7),
(24, 8), (24, 1),
(25, 2), (25, 3),
(26, 4), (26, 5),
(27, 6), (27, 7),
(28, 8), (28, 1),
(29, 2), (29, 3),
(30, 4), (30, 5);

INSERT INTO UserProjectInterests (user_id, interest_id) VALUES
(1, 1), (1, 2),
(2, 3), (2, 4),
(3, 5), (3, 6),
(4, 1), (4, 2),
(5, 3), (5, 4),
(6, 5), (6, 6),
(7, 7), (7, 8),
(8, 1), (8, 2),
(9, 3), (9, 4),
(10, 5), (10, 6),
(11, 1), (11, 2),
(12, 3), (12, 4),
(13, 5), (13, 6),
(14, 7), (14, 8),
(15, 1), (15, 2),
(16, 3), (16, 4),
(17, 5), (17, 6),
(18, 1), (18, 2),
(19, 3), (19, 4),
(20, 5), (20, 6),
(21, 1), (21, 2),
(22, 3), (22, 4),
(23, 5), (23, 6),
(24, 7), (24, 8),
(25, 1), (25, 2),
(26, 3), (26, 4),
(27, 5), (27, 6),
(28, 7), (28, 8),
(29, 1), (29, 2),
(30, 3), (30, 4);

